### ISSUE TITLE
Images on irrigation tips for Sq ft gardening fail to load.

### ISSUE THREAD

**Issue by undergroundrebel** [iogeek/Gardening4Engineers#3]
![image](https://user-images.githubusercontent.com/19354454/103161244-bc4f2480-4793-11eb-9572-ce82880ad05c.png)

**Comment by iogeek** [comment]
oops.  I did not double check the "behind the scenes" Jekyll (embedded in the markdown) rendered correctly.  Should be fixed with latest merge.
